name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.4
      - run: ko publish --base-import-paths ./cmd/model_downloader -t ${GITHUB_SHA::7}
      - working-directory: ./cmd/dataset_tokenizer
        run: ko publish --base-import-paths . -t ${GITHUB_SHA::7}
